"""1-click GitHub issue creator (Demeter Wave 3 Hybrid Layer 1).

PRD pitch differentiator: convert a Nemesis finding into a GitHub issue with
evidence chain pre-filled body + suggested label. Uses the OAuth access token
(decrypted via crypto.py) from the authenticated user.

Scopes required: write:issues (per `app/config.py` GITHUB_OAUTH_SCOPES locked).

Anti-pattern Lock 3: token decrypted at use site only, never logged.
"""
from __future__ import annotations

import logging
from typing import Any

import httpx
from pydantic import BaseModel

from app.services.crypto import decrypt_token

logger = logging.getLogger("demeter.github_issue")


class IssueCreateRequest(BaseModel):
    """Request from finding endpoint."""

    repo_full_name: str  # owner/repo
    title: str
    body: str
    labels: list[str] = []


class IssueCreateResult(BaseModel):
    """GitHub API response (subset)."""

    issue_number: int
    issue_url: str
    state: str


class GitHubIssueCreator:
    """Wraps GitHub REST API POST /repos/{owner}/{repo}/issues."""

    def __init__(self, base_url: str = "https://api.github.com") -> None:
        self._base_url = base_url

    async def create_issue(
        self,
        *,
        encrypted_token: str,
        request: IssueCreateRequest,
    ) -> IssueCreateResult:
        """POST /repos/{owner}/{repo}/issues with bearer auth.

        Raises:
            ValueError: token decrypt failure.
            httpx.HTTPStatusError: GitHub API rejection.
        """
        access_token = decrypt_token(encrypted_token)
        if access_token is None:
            raise ValueError("token decrypt failed")

        url = f"{self._base_url}/repos/{request.repo_full_name}/issues"
        payload: dict[str, Any] = {
            "title": request.title,
            "body": request.body,
        }
        if request.labels:
            payload["labels"] = request.labels

        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(
                url,
                json=payload,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
            )
            resp.raise_for_status()
            data = resp.json()
        return IssueCreateResult(
            issue_number=int(data["number"]),
            issue_url=str(data["html_url"]),
            state=str(data.get("state", "open")),
        )


def build_evidence_body(finding: dict[str, Any]) -> str:
    """Pre-fill body with evidence chain from finding row.

    Format includes finding category, severity, file path, line range, CVSS
    if available, suggested fix. Markdown-formatted for GitHub issue body.
    """
    lines = [
        f"## Finding: {finding.get('title', 'untitled')}",
        "",
        f"**Category**: `{finding.get('category', 'unknown')}`",
        f"**Severity**: `{finding.get('severity', 'unknown')}`",
        f"**Repository**: `{finding.get('repo_full_name', 'unknown')}`",
        "",
        "### Location",
        "",
        f"- File: `{finding.get('file_path', 'unknown')}`",
        f"- Lines: {finding.get('line_start', 0)}-{finding.get('line_end', 0)}",
        f"- Building: `{finding.get('building_id', 'unknown')}`",
        "",
    ]
    cvss_vector = finding.get("cvss_vector")
    cvss_score = finding.get("cvss_base_score")
    if cvss_vector or cvss_score:
        lines.extend(
            [
                "### CVSS",
                "",
                f"- Vector: `{cvss_vector or 'not scored'}`",
                f"- Base Score: `{cvss_score or 'not scored'}`",
                "",
            ]
        )
    description = finding.get("description")
    if description:
        lines.extend(["### Description", "", description, ""])
    suggested_fix = finding.get("suggested_fix")
    if suggested_fix:
        lines.extend(["### Suggested Fix", "", suggested_fix, ""])

    lines.extend(
        [
            "### Provenance",
            "",
            f"- Scan run: `{finding.get('scan_run_id', 'unknown')}`",
            f"- Finding ID: `{finding.get('finding_id', 'unknown')}`",
            f"- Detected at: `{finding.get('detected_at', 'unknown')}`",
            "",
            "Generated by Codeplex Chronicle Health Mode (Nemesis detector + Argus CVSS).",
        ]
    )
    return "\n".join(lines)


def suggest_label(category: str | None, severity: str | None) -> list[str]:
    """Suggest GitHub issue labels based on finding category + severity."""
    labels: list[str] = ["codeplex-chronicle"]
    if category:
        labels.append(f"category:{category}")
    if severity:
        labels.append(f"severity:{severity}")
    if category in ("hardcoded-secret", "missing-auth", "unsafe-sql"):
        labels.append("security")
    return labels


__all__ = [
    "GitHubIssueCreator",
    "IssueCreateRequest",
    "IssueCreateResult",
    "build_evidence_body",
    "suggest_label",
]
