/**
 * [MOCK Wave 1, real Wave 3 Demeter]
 *
 * Hardcoded dashboard payload shaped per `DashboardData`. Selene Wave 1 wires
 * this into `useDashboardData` so the dashboard route renders end-to-end without
 * backend. Wave 3 Demeter swaps with a Postgres event-store query (same shape,
 * Pydantic alias generator emits matching camelCase JSON).
 *
 * Voice anchors per Designer Prompt 3 intent.md:
 * - briefing: "Sprint 14 ships in 3 days. Velocity holding at 18 points.
 *   One drift pattern triggered in the auth district."
 * - KPI strip 4 tiles (Velocity, Cycle time, Change failure rate, Deploys).
 * - Pattern E (OpenSpec drift) is the firing site -> auth district highlight.
 */

import type { DashboardData } from './types';

export const mockDashboardData: DashboardData = {
  briefing:
    'Sprint 14 ships in 3 days. Velocity holding at 18 points. One drift pattern triggered in the auth district.',
  currentSprint: 'Sprint 14',
  lastRefresh: '2026-05-12T08:42:00+07:00',
  kpis: [
    {
      id: 'velocity',
      label: 'Velocity',
      value: 18,
      unit: 'points',
      unitShort: 'pts',
      trend: 'flat',
      deltaPercent: 0,
      deltaUnit: 'pts',
      note: 'vs last sprint',
    },
    {
      id: 'cycle-time',
      label: 'Cycle time',
      value: 2.4,
      unit: 'days',
      unitShort: 'd',
      trend: 'down',
      deltaPercent: -8,
      deltaUnit: '%',
      note: 'p50, last 30 days',
    },
    {
      id: 'change-failure-rate',
      label: 'Change failure rate',
      value: 6.1,
      unit: 'percent',
      unitShort: '%',
      trend: 'up',
      deltaPercent: 1.2,
      deltaUnit: 'pp',
      note: 'rolling 4 weeks',
    },
    {
      id: 'deploys-this-week',
      label: 'Deploys this week',
      value: 11,
      unit: 'count',
      trend: 'up',
      deltaPercent: 2,
      deltaUnit: '',
      note: 'vs last week',
    },
  ],
  burndown: [
    { day: 0, idealRemaining: 50, actualRemaining: 50 },
    { day: 1, idealRemaining: 45, actualRemaining: 48 },
    { day: 2, idealRemaining: 40, actualRemaining: 44 },
    { day: 3, idealRemaining: 35, actualRemaining: 41 },
    { day: 4, idealRemaining: 30, actualRemaining: 36 },
    { day: 5, idealRemaining: 25, actualRemaining: 30 },
    { day: 6, idealRemaining: 20, actualRemaining: 25 },
    { day: 7, idealRemaining: 15, actualRemaining: 20 },
    { day: 8, idealRemaining: 10, actualRemaining: 14 },
    { day: 9, idealRemaining: 5, actualRemaining: 9 },
    { day: 10, idealRemaining: 0, actualRemaining: 5 },
  ],
  burndownMeta: {
    sprintLabel: 'Sprint 14',
    todayIndex: 8,
    daysToShip: 3,
    pointsRemaining: 14,
    pointsTotal: 50,
  },
  velocity: [
    { sprintLabel: 'S7', pointsCompleted: 14, endDate: '2026-01-30' },
    { sprintLabel: 'S8', pointsCompleted: 16, endDate: '2026-02-13' },
    { sprintLabel: 'S9', pointsCompleted: 15, endDate: '2026-02-27' },
    { sprintLabel: 'S10', pointsCompleted: 19, endDate: '2026-03-13' },
    { sprintLabel: 'S11', pointsCompleted: 17, endDate: '2026-03-27' },
    { sprintLabel: 'S12', pointsCompleted: 16, endDate: '2026-04-10' },
    { sprintLabel: 'S13', pointsCompleted: 18, endDate: '2026-04-24' },
    { sprintLabel: 'S14', pointsCompleted: 18, endDate: '2026-05-15', isCurrent: true },
  ],
  milestones: [
    {
      id: 'm-1',
      label: 'Manager dashboard v1',
      percentComplete: 72,
      daysRemaining: 3,
      blockersCount: 1,
    },
    {
      id: 'm-2',
      label: 'OpenSpec dual-folder',
      percentComplete: 90,
      daysRemaining: 1,
      blockersCount: 0,
    },
  ],
  contributors: [
    {
      githubLogin: 'finerium',
      displayName: 'Ghaisan Badruzaman',
      avatarUrl: 'https://avatars.githubusercontent.com/u/0?v=4',
      prsOpened: 7,
      prsMerged: 5,
      reviewsSubmitted: 9,
      linesAdded: 1820,
      linesDeleted: 740,
      issuesOpened: 3,
      issuesClosed: 4,
    },
    {
      githubLogin: 'hafizfauzan',
      displayName: 'Hafiz Fauzan',
      avatarUrl: 'https://avatars.githubusercontent.com/u/0?v=4',
      prsOpened: 5,
      prsMerged: 4,
      reviewsSubmitted: 6,
      linesAdded: 1240,
      linesDeleted: 380,
      issuesOpened: 2,
      issuesClosed: 3,
    },
    {
      githubLogin: 'athena-ai',
      displayName: 'Athena (resident)',
      avatarUrl: 'https://avatars.githubusercontent.com/u/0?v=4',
      prsOpened: 4,
      prsMerged: 3,
      reviewsSubmitted: 11,
      linesAdded: 980,
      linesDeleted: 1120,
      issuesOpened: 1,
      issuesClosed: 2,
    },
    {
      githubLogin: 'argus-ai',
      displayName: 'Argus (resident)',
      avatarUrl: 'https://avatars.githubusercontent.com/u/0?v=4',
      prsOpened: 3,
      prsMerged: 2,
      reviewsSubmitted: 14,
      linesAdded: 420,
      linesDeleted: 180,
      issuesOpened: 5,
      issuesClosed: 4,
    },
    {
      githubLogin: 'apollo-ai',
      displayName: 'Apollo (resident)',
      avatarUrl: 'https://avatars.githubusercontent.com/u/0?v=4',
      prsOpened: 2,
      prsMerged: 2,
      reviewsSubmitted: 7,
      linesAdded: 360,
      linesDeleted: 220,
      issuesOpened: 1,
      issuesClosed: 2,
    },
    {
      githubLogin: 'clio-ai',
      displayName: 'Clio (resident)',
      avatarUrl: 'https://avatars.githubusercontent.com/u/0?v=4',
      prsOpened: 2,
      prsMerged: 1,
      reviewsSubmitted: 5,
      linesAdded: 280,
      linesDeleted: 90,
      issuesOpened: 0,
      issuesClosed: 1,
    },
  ],
  drifts: [
    {
      pattern: 'A',
      patternLabel: 'Stale closed issue',
      patternDescription: 'closed > 30 days, no follow-up linked',
      severity: 'low',
      severityLevel: 1,
      trend: 'flat',
      count: 4,
      resolutionRate: 0.82,
    },
    {
      pattern: 'B',
      patternLabel: 'Closed without merge',
      patternDescription: 'PR closed, branch alive, no replacement PR',
      severity: 'medium',
      severityLevel: 2,
      trend: '+1',
      count: 2,
      resolutionRate: 0.55,
    },
    {
      pattern: 'C',
      patternLabel: 'Spec-implementation lag',
      patternDescription: 'merged code not reflected in OpenSpec change',
      severity: 'medium',
      severityLevel: 3,
      trend: 'flat',
      count: 3,
      resolutionRate: 0.6,
    },
    {
      pattern: 'D',
      patternLabel: 'Reopened cycle',
      patternDescription: 'issue closed and reopened > 2 times in 14 days',
      severity: 'high',
      severityLevel: 4,
      trend: '-1',
      count: 1,
      resolutionRate: 0.4,
    },
    {
      pattern: 'E',
      patternLabel: 'OpenSpec drift',
      patternDescription: 'Folder A spec ahead of merged implementation',
      district: 'auth',
      severity: 'critical',
      severityLevel: 5,
      trend: '+2',
      count: 1,
      resolutionRate: 0.15,
    },
  ],
  refactorProposals: [
    {
      id: 'refactor-auth-session-store',
      title: 'Split session store from auth router',
      stage: 'proposed',
      authorResident: 'Athena',
      authorLogin: '',
      ageLabel: '2h ago',
      createdAt: '2026-05-12T06:30:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-auth-session-store',
    },
    {
      id: 'refactor-event-bus-pubsub',
      title: 'Migrate event bus to typed pubsub',
      stage: 'proposed',
      authorResident: 'Athena',
      authorLogin: '',
      ageLabel: '5h ago',
      createdAt: '2026-05-12T03:30:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-event-bus-pubsub',
    },
    {
      id: 'refactor-tree-sitter-lazy',
      title: 'Lazy-load tree-sitter language packs',
      stage: 'proposed',
      authorResident: 'user',
      authorLogin: 'finerium',
      ageLabel: '1d ago',
      createdAt: '2026-05-11T09:30:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-tree-sitter-lazy',
    },
    {
      id: 'refactor-llm-gateway-retry',
      title: 'Add retry simplified prompt to LLM gateway',
      stage: 'simulating',
      authorResident: 'Athena',
      authorLogin: '',
      ageLabel: '6h ago',
      createdAt: '2026-05-12T02:30:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-llm-gateway-retry',
    },
    {
      id: 'refactor-postgres-connection-pool',
      title: 'Tune Postgres connection pool defaults',
      stage: 'simulating',
      authorResident: 'user',
      authorLogin: 'hafizfauzan',
      ageLabel: '12h ago',
      createdAt: '2026-05-11T20:30:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-postgres-connection-pool',
    },
    {
      id: 'refactor-resident-cache',
      title: 'Add semantic cache to resident replies',
      stage: 'drafted',
      authorResident: 'Athena',
      authorLogin: '',
      ageLabel: '1d ago',
      createdAt: '2026-05-11T09:00:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-resident-cache',
    },
    {
      id: 'refactor-three-instanced-mesh',
      title: 'Switch city render to instancedMesh raw',
      stage: 'drafted',
      authorResident: 'user',
      authorLogin: 'finerium',
      ageLabel: '2d ago',
      createdAt: '2026-05-10T09:00:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-three-instanced-mesh',
    },
    {
      id: 'refactor-openspec-dual-folder',
      title: 'Dual-folder OpenSpec strategy A vs B',
      stage: 'accepted',
      authorResident: 'Athena',
      authorLogin: '',
      ageLabel: '3d ago',
      createdAt: '2026-05-09T09:00:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-openspec-dual-folder',
    },
    {
      id: 'refactor-fastapi-tree-sitter-init',
      title: 'Boot-time tree-sitter lazy init',
      stage: 'archived',
      authorResident: 'user',
      authorLogin: 'hafizfauzan',
      ageLabel: '6d ago',
      createdAt: '2026-05-06T09:00:00+07:00',
      openspecChangePath: 'openspec/changes/refactor-fastapi-tree-sitter-init',
    },
  ],
  repos: [
    {
      fullName: 'Finerium/codeplexRefactory',
      label: 'codeplexRefactory',
      branch: 'main',
      openPRs: 4,
      openIssues: 7,
      driftCount: 1,
      statusDot: 'green',
      sparkline: [3, 5, 6, 4, 7, 5, 8, 6, 7, 9, 6, 7, 8, 7],
    },
    {
      fullName: 'Finerium/codeplex-demo-nodegoat',
      label: 'nodegoat-demo',
      branch: 'main',
      openPRs: 2,
      openIssues: 5,
      driftCount: 4,
      statusDot: 'red',
      sparkline: [1, 2, 1, 3, 2, 4, 2, 3, 1, 2, 3, 1, 2, 2],
    },
    {
      fullName: 'Finerium/codeplex-demo-fastapi-fullstack',
      label: 'fastapi-fullstack',
      branch: 'main',
      openPRs: 3,
      openIssues: 4,
      driftCount: 0,
      statusDot: 'green',
      sparkline: [2, 4, 3, 5, 6, 4, 7, 5, 6, 7, 6, 8, 7, 9],
    },
    {
      fullName: 'Finerium/codeplex-residents',
      label: 'residents',
      branch: 'main',
      openPRs: 1,
      openIssues: 3,
      driftCount: 2,
      statusDot: 'yellow',
      sparkline: [4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 4],
    },
    {
      fullName: 'Finerium/codeplex-infra',
      label: 'codeplex-infra',
      branch: 'main',
      openPRs: 0,
      openIssues: 1,
      driftCount: 0,
      statusDot: 'green',
      sparkline: [1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2],
    },
  ],
  cityPreviewMeta: {
    repoSlug: 'Finerium/codeplexRefactory',
    districtCount: 6,
    flaggedDistrict: 'auth',
    lastBuildAt: '2026-05-12T08:18:00+07:00',
    citizenCount: 4200,
  },
};
