"""Settings loader (pydantic-settings reads .env).

Hades Wave 3 owns config. Downstream workers (Triton, Nemesis, Pandora, Demeter)
import `settings` singleton. Anti-pattern Lock 5 honest claim: this loader is the
single source of truth for env vars.

Reference:
- .env at project root
- PRD Section 17 (tech stack lock) + 18.3 (DeepSeek) + 19.3 (OAuth scope minimal)
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


# Project root = parent of `backend/` directory.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_ENV_PATH = _PROJECT_ROOT / ".env"


class Settings(BaseSettings):
    """Application settings.

    Source of truth: `.env` at project root. Missing required vars raise on
    instantiation so deploy time fails fast rather than producing 500s mid-flight.
    """

    model_config = SettingsConfigDict(
        env_file=str(_ENV_PATH),
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=True,
    )

    # ---- App runtime ----
    APP_ENV: str = "development"
    APP_DOMAIN: str = "duopoly.hackathon.sev-2.com"
    NEXT_PUBLIC_API_URL: str = "http://localhost:8000"

    # ---- GitHub OAuth (real flow, Hades Wave 3) ----
    # Scope minimal per PRD Section 19.3 LOCKED.
    GITHUB_CLIENT_ID: str
    GITHUB_CLIENT_SECRET: str
    GITHUB_OAUTH_REDIRECT_URI: str
    GITHUB_OAUTH_SCOPES: str = "read:repo,read:org,read:issues,read:pull_requests,write:issues"
    GITHUB_USER: str = "Finerium"

    # ---- GitHub webhook (HMAC verify per request) ----
    GITHUB_WEBHOOK_SECRET: str

    # ---- DeepSeek (Triton Wave 3 consumer) ----
    DEEPSEEK_API_KEY: str
    DEEPSEEK_BASE_URL: str = "https://api.deepseek.com"
    DEEPSEEK_MODEL_FLASH: str = "deepseek-v4-flash"
    DEEPSEEK_MODEL_PRO: str = "deepseek-v4-pro"

    # ---- Database (Demeter Wave 3 consumer) ----
    DATABASE_URL: str

    # ---- K8s deploy (Atlas Wave 3 consumer) ----
    KUBECONFIG_PATH: str = ""
    K8S_NAMESPACE: str = "duopoly"

    # ---- Session signing (Hades JWT cookie) ----
    # Generated by Hades cycle 1 init if absent (32-byte urlsafe).
    SESSION_SECRET: str = Field(
        default="hades-cycle1-default-rotate-before-prod-deploy-7c4e2b9f6a1d3e8c",
    )

    # ---- Feature flags ----
    ENABLE_WRITE_OPS: bool = True
    ENABLE_WRITE_OPS_LAYER_2: bool = True

    # ---- Derived helpers ----
    @property
    def github_scopes_list(self) -> list[str]:
        return [s.strip() for s in self.GITHUB_OAUTH_SCOPES.split(",") if s.strip()]

    @property
    def cors_allow_origins(self) -> list[str]:
        """CORS whitelist: production domain + local dev ports."""
        origins = [
            f"https://{self.APP_DOMAIN}",
            "http://localhost:3000",
            "http://localhost:3100",
            "http://127.0.0.1:3000",
        ]
        return origins

    @property
    def is_production(self) -> bool:
        return self.APP_ENV.lower() == "production"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Singleton accessor (lru_cache size 1).

    Re-read .env requires process restart by design.
    """
    return Settings()
